version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: seloserver
    env_file:
      - ./server/.env
    environment:
      - PORT=3005
    expose:
      - "3005"
    volumes:
      - uploads_data:/home/node/app/dist/src/uploads
    networks: 
      - boraimpactar2

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: seloclient
    env_file:
      - ./client/.env
    environment:
      - PORT=8005
      - NEXT_PUBLIC_API_BASE=/seloresponsaback
    expose:
      - "8005"
    networks: 
      - boraimpactar2

  # nginx:
  #   image: nginx:1.27-alpine
  #   volumes:
  #     - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - client
  #     - server
  #   networks: [appnet]

networks:
  boraimpactar2:
    external: true

volumes:
  uploads_data: